---
title       : R的ETL流程
subtitle    : 
author      : Cheng Yu Lin (aha)
job         : 
license     : by-sa
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
ext_widgets : {rCharts: libraries/nvd3}
widgets     : [mathjax, quiz, bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---


## 故事的起源

> 1. 房價節節高升
> 2. 大熊被抓了
> 3. 房價真的太高了嗎?

--- &twocol

## 資料在哪裡

*** =left
### 你想知道什麼資料?

> 1. GDP
> 2. 房貸餘額
> 3. 股價
> 4. 新聞

*** =right
### 可能的來源?
> 1. 政府公開資料
> 2. 新聞
> 3. 股市


--- .quote

<q>即便知道資料在哪，可是資料還是如同`一盤散沙`</q>

---  

## ETL

> 1. Extraction
> 2. Transformation
> 3. Loading

--- 

## Extraction

### 讀入資料 - read.table

至少要記得的 `read.table`
```
DF = read.table(file='檔案路徑',sep=",",stringsAsFactors=F,header=T)
```
- 輸出形態為`Data Frame`
- file 就是指讀入的檔案路徑
- sep 指的是欄位分割用的符號,通常csv檔案格式是透過`,`做分割
- stringsAsFactors 預設是`True`, 會讓讀入的字串都用Factor形態儲存，那麼資料就會轉為整數儲存與額外的對照表
- header 預設是`False`，表示第一行是不是表格標頭，作為輸出的dataframe欄位名的colnames

---  .quote

<q> 開始動手做吧!</q>

--- .quote 

<q> 等等 先安裝幾個建議的套件</q>

> - `dplyr` 可用類似SQL語法操作data frome
> - `xts` 處理時間格式好用的套件
> - `gdata` 可以處理Excel 2007以上的文件


--- .quote 

<q> 等等 先安裝幾個建議的套件</q>

- `dplyr` 可用類似SQL語法操作data frome
- `xts` 處理時間格式好用的套件
- `gdata` 可以處理Excel 2007以上的文件

```
install.packages("dplyr")
install.packages("xts")
install.packages("gdata")
```


--- .quote

<q> 好! 開始動手做吧!</q>


--- .quote 

<q> 好! 開始動手做吧!</q>

<q> `資料勒？！`</q>

---

## 開始收集資料(房貸餘額)

<iframe src = 'https://survey.banking.gov.tw/statis/stmain.jsp?sys=100&funid=r100' height='600px'></iframe>

---
## 開始收集資料

### 房貸餘額,直接下載現成的csv檔案

- 直接到[https://raw.githubusercontent.com/ntuaha/TWFS/master/db/cl_info_other.csv](https://raw.githubusercontent.com/ntuaha/TWFS/master/db/cl_info_other.csv)下載檔案


### 將資料讀入


```{r}
library(dplyr)
Cl_info = read.table(file='./cl_info_other.csv',header=T,sep=",",stringsAsFactors=F)
Cl_info = mutate(Cl_info,data_dt = as.POSIXct(data_dt),
                 bank_code = as.factor(bank_code),etl_dt = as.POSIXct(etl_dt))
View(Cl_info)
```

<br/>
> - 到這裡已經完成第一次的資料`Extraction`與`Transformation`了！

--- .quote

<q>看見資料了!但是剛剛處理過程中的`mutate`是什麼?</q>


--- .quote

<q>看見資料了!但是剛剛處理過程中的`mutate`是什麼?</q>

<q> 在`R`中用來做__資料清理__與__資料處理__好用的套件`dplyr`其中之一的函式<q>

--- 

## dplyr 介紹 - select

### `select` 函式，用來__挑選__`欄位`
```
Cl_info_part = select(Cl_info,date_dt,bank_nm,mortgage_bal)
```
- 輸出data frame
- 第一個參數為輸入的data frame
- 後續參數為選取的欄位名稱

<br/>
###  給熟悉`SQL`的使用者

```
select data_dt,bank_nm,mortgage_bal from Cl_info;
```



---

## dplyr 介紹 - filter

### `filter` 函式，用來__保留__要留下的`資料列`

```
Cl_info_part2 = filter(Cl_info,mortgage_bal>1000000)
```

- 輸出data frame
- 第一個參數為輸入的data frame
- 第二個參數為邏輯運算式，可用data frame裡的欄位，當結果為`True`時，該筆資料列保留

<br/>
### 給熟悉`SQL`的使用者
```
select * from Cl_info where mortgage>1000000;
```



---


## dplyr 介紹 - mutate

### `mutate` 用來增加**非彙總**計算`欄位`

```
Cl_info_part3 = filter(Cl_info,mortage = mortgage/1000000)
```
- 輸出data frame
- 第一個參數為輸入的 data frame
- 第二參數為計算式，也可以用來當做**轉換資料形態**，**變更欄位為名稱**使用

<br/>
### 給熟悉`SQL`的使用者

```
select mmortgage/1000000 as mortage from Cl_info;
```

---

## dplyr 介紹 - arrange

### `arrange` 用來重新排序

```
Cl_info_part4 = arrange(Cl_info,mortage,desc(data_dt))
```
- 輸出data frame
- 第一個參數為輸入的 data frame
- 後續參數為排序用欄位，預設遞增，可以透過`desc()`變成遞減排序

<br/>
### 給熟悉`SQL`的使用者

```
select * from Cl_info order by mortage,data_dt desc ;
```

--- .quote

<q>下一個?</q>


--- .quote

<q>下一個?</q>

<q>別急，讓我們來練習抓下一個檔案，用剛剛講的指令讀入</q>

--- 

## 開始收集資料(GDP)

<iframe src = 'http://ebas1.ebas.gov.tw/pxweb/Dialog/NI.asp' height='600px'></iframe>

---

## 開始收集資料(GDP)

1. GDP從直接下載`國民生產毛額之處分`
2. 季(1980之後）
3. 選**全部的日期**
4. 選**全部的計價方式**
5. 項目選**GDP**
6. 總類選**原始值**
7. 按繼續後，選**從螢幕顯示Excel檔**
8. 開啟後，**另存新檔成csv檔**
9. 開回`RStudio` 開始處理資料


--- .quote

<q>練習讀入與創建一個變數`GDP`</q>

--- .quote


<q>答案</q>

```
GDP = read.table(file='檔案位置',sep=",",stringsAsFactors=F,header=F)
```

--- .quote


<q>答案</q>

```
GDP = read.table(file='檔案位置',sep=",",stringsAsFactors=F,header=F)
```
<br>

<q>輸入`View(GDP)`觀察`GDP`會發現怎麼前後有很多列的資料是不要的</q>

---


---

## dplyr 介紹 - group_by, summarise

### `group_by` 用來將資料包裝成一組，做後續的`彙總`處;`summarise`則用來做後續的各類彙總操作

```
Cl_info_part5 = mutate(Cl_info,time=data_dt) #已看過
Cl_info_part6 = group_by(Cl_info_part5,time) #先匯總
Cl_info_part7 = summarise(Cl_info_part6,
        mortage_total_bal = sum(mortgage_bal, na.rm = TRUE),
        mortage_total_cnt = sum(mortgage_cnt,na.rm=TRUE))
```
- 輸出data frame
- 第一個參數為輸入的 data frame
- 第二個欄位之後都是用來group by/summarise 的欄位
- 後續函數用來處理匯總運算

<br/>
### 給熟悉`SQL`的使用者

```
select sum(mortgage_bal) as mortage_total_bal, sum(mortgage_cnt) as mortage_total_cnt from Cl_info group by time ;
```

--- .quote

<q>group by 可加先下也可不下，不下的情況是直接對**全部**資料做集匯總運算 </q>


---

##彙總函數 summarise

可以使用的函數如下所列

 - mean  平均值
 - sum   加總 
 - n     計算個數  例如: A B B C   輸出4 
 - n_distinct 計算不同物件的個數 例: A B B C 輸出3
 - first 該群體第一個，可配合group by 使用
 - last  該群體最後一個，可配合group by 使用
 - nth   該群體的第n個，可配合group by 使用
 - min, max 最大最小值
 - median 中位數
 - IQR   就是IQR  ＃待驗證

---

---

## Reference

1. [http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html](http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html)
2. 
